### ISSUE TITLE
Need test case for duplicate entries in manifest.yaml

### ISSUE THREAD

**Issue by huydoan2** [apache/openwhisk-wskdeploy#1102]
We need a test case for expected behavior when there are duplicated entries in `manifest.yaml` such as:

```
packages:
  helloworld:
    actions:
      hello1:
        function: ../src/integration/helloworld/actions/hello.js
        limits:
          timeout: 1
          timeout: 600000
```

https://github.com/apache/openwhisk-wskdeploy/pull/1101 eliminated a similar test due to a package change and the behavior also changes.
