### ISSUE TITLE
Programming Guide: Sequences example (with web actions)

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk-wskdeploy#847]
See: https://github.com/apache/incubator-openwhisk-wskdeploy/blob/master/tests/src/integration/websequence/manifest.yaml

```
        sequences:
            greeting-sequence-1:
                actions: greeting-1, greeting-2
                web: true
            greeting-sequence-2:
                actions: greeting-1, greeting-2
                web: raw
```

for example, although the actions for "greeting-1" and "greeting-2" may not be declared as web actions, the sequence "greating-sequence-1" produces an action (sequence) that is itself a web action.
